#:schema https://mise.jdx.dev/schema/mise.json

[tools]
go = '1.23.6'
golangci-lint = "1.63.4"
# renovate: datasource=github-tags depName=gotestyourself/gotestsum
gotestsum = "v1.12.0"
# renovate: datasource=go depName=go.uber.org/mock/mockgen
"go:go.uber.org/mock/mockgen" = "v0.5.0"
# renovate: datasource=go depName=golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment
# "go:golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment" = "v0.29.0"
