#:schema https://mise.jdx.dev/schema/mise.json

[tools]
go = '1.24.4'
golangci-lint = "2.1.6"
# renovate: datasource=github-tags depName=gotestyourself/gotestsum
gotestsum = "v1.12.2"
# renovate: datasource=go depName=go.uber.org/mock/mockgen
"go:go.uber.org/mock/mockgen" = "v0.5.2"
# renovate: datasource=go depName=golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment
# "go:golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment" = "v0.35.0"
# renovate: datasource=github-tags depName=jmattheis/goverter
"go:github.com/jmattheis/goverter/cmd/goverter" = "v1.8.3"
